import type { Application, Store, User, ActivityLog } from "./types"

export const stores: Store[] = [
  {
    id: "STORE001",
    name: "Tech World",
    address: "123 Main Street, Dhaka",
    phone: "01712345678",
    email: "info@techworld.com",
    manager: "John Doe",
    status: "active",
  },
  {
    id: "STORE002",
    name: "Electronics Hub",
    address: "456 Commercial Road, Chittagong",
    phone: "01798765432",
    email: "contact@electronicshub.com",
    manager: "Jane Smith",
    status: "active",
  },
  {
    id: "STORE003",
    name: "Digital Plaza",
    address: "789 Shopping Center, Sylhet",
    phone: "01687654321",
    email: "support@digitalplaza.com",
    manager: "Mike Johnson",
    status: "active",
  },
]

export const initialApplications: Application[] = [
  {
    id: "APP001",
    customerName: "Ahmed Hassan",
    phoneNumber: "01712345678",
    email: "ahmed@example.com",
    cardNumber: "4532-1234-5678-9012",
    clientId: "CLI001",
    amount: 50000,
    tenure: 12,
    date: "2024-01-15",
    status: "approved",
    store: "Tech World",
    merchant: "John Doe",
    approvalCode: "APV001234",
    notes: "Regular customer with good credit history",
    timeline: [
      {
        id: "TL001",
        timestamp: "2024-01-15T10:00:00Z",
        action: "Application Submitted",
        user: "Ahmed Hassan",
        details: "Application submitted for EMI approval",
      },
      {
        id: "TL002",
        timestamp: "2024-01-15T14:30:00Z",
        action: "Status Updated",
        user: "John Doe",
        details: "Application approved",
        status: "approved",
      },
    ],
  },
  {
    id: "APP002",
    customerName: "Fatima Rahman",
    phoneNumber: "01798765432",
    email: "fatima@example.com",
    cardNumber: "5432-9876-5432-1098",
    clientId: "CLI002",
    amount: 75000,
    tenure: 18,
    date: "2024-01-16",
    status: "pending",
    store: "Electronics Hub",
    merchant: "Jane Smith",
    approvalCode: "",
    notes: "Pending verification of documents",
    timeline: [
      {
        id: "TL003",
        timestamp: "2024-01-16T09:15:00Z",
        action: "Application Submitted",
        user: "Fatima Rahman",
        details: "Application submitted for EMI approval",
      },
    ],
  },
  {
    id: "APP003",
    customerName: "Mohammad Ali",
    phoneNumber: "01687654321",
    email: "ali@example.com",
    cardNumber: "4111-1111-1111-1111",
    clientId: "CLI003",
    amount: 30000,
    tenure: 6,
    date: "2024-01-17",
    status: "verified",
    store: "Digital Plaza",
    merchant: "Mike Johnson",
    approvalCode: "",
    notes: "Documents verified, awaiting final approval",
    timeline: [
      {
        id: "TL004",
        timestamp: "2024-01-17T11:20:00Z",
        action: "Application Submitted",
        user: "Mohammad Ali",
        details: "Application submitted for EMI approval",
      },
      {
        id: "TL005",
        timestamp: "2024-01-17T16:45:00Z",
        action: "Status Updated",
        user: "Mike Johnson",
        details: "Documents verified",
        status: "verified",
      },
    ],
  },
]

export const initialUsers: User[] = [
  {
    id: "USER001",
    name: "Admin User",
    email: "admin@smartemi.com",
    role: "admin",
    status: "active",
  },
  {
    id: "USER002",
    name: "John Doe",
    email: "john@techworld.com",
    role: "merchant",
    store: "Tech World",
    status: "active",
  },
  {
    id: "USER003",
    name: "Jane Smith",
    email: "jane@electronicshub.com",
    role: "merchant",
    store: "Electronics Hub",
    status: "active",
  },
]

export const initialActivityLogs: ActivityLog[] = [
  {
    id: "LOG001",
    timestamp: "2024-01-15T10:00:00Z",
    user: "Ahmed Hassan",
    action: "Application Created",
    details: "New EMI application submitted for ৳50,000",
    applicationId: "APP001",
    type: "create",
  },
  {
    id: "LOG002",
    timestamp: "2024-01-15T14:30:00Z",
    user: "John Doe",
    action: "Status Updated",
    details: "Application APP001 status changed from pending to approved",
    applicationId: "APP001",
    type: "status_update",
  },
  {
    id: "LOG003",
    timestamp: "2024-01-16T09:15:00Z",
    user: "Fatima Rahman",
    action: "Application Created",
    details: "New EMI application submitted for ৳75,000",
    applicationId: "APP002",
    type: "create",
  },
]
